### PR TITLE
Cleaning up make workflow

### PR DESCRIPTION
**Pull request by mbjoseph**
Recent changes to dplyr necessitated a tweak to the make build process.
I have also removed a tutorial on pymodis, which is redundant with the
docs for that package.

### CODE REVIEW

**Comment by lwasser** [comment]
Heya max!! just a quick question. Did you reclone the repo before this push? Just wondering.

It’s not a huge deal but I had cleaned everything up and if you didn’t – I may need to do a reclean (which is totally OK because I forgot to mention this to you I’m pretty sure). Plus – what’s new with dplyr? Uh oh!

**Comment by mbjoseph** [comment]
Yep - I deleted my local copy and then cloned this one!

**Comment by lwasser** [comment]
Oh you clever psychic human you. Great!! ☺

**Comment by mbjoseph** [comment]
Nothing huge with dplyr, but wheras previously you could reference an outside data frame from within a call to mutate() that has the same name as a column of the data frame you're currently working with, now you cannot (which is probably good): https://github.com/earthlab/earthlab.github.io/pull/320/files#diff-8e3ff44e534d3628c4d381c8d2da7024R124

**Pull request merged**
