### PR TITLE
turning off anoying pagination error

### PR DESCRIPTION
**Pull request by lwasser**
THIS is making TRAVIS angry @mbjoseph BUT it builds locally. Please help me understand how TRAVIS tests the build.

### CODE REVIEW

**Comment by mbjoseph** [comment]
Ok I fixed it. Now Travis CI will only try to build if there is a .travis.yml file present. In all but the feature/minimal-travis-ci branch, this file does not currently exist, so pushing to anything other than feature/minimal-travis-ci should not trigger a build!

**Comment by lwasser** [comment]
woo hoo. it stopped yelling at me. But now how do we know if there are build errors?

**Comment by mbjoseph** [comment]
We won't until I fix and merge the branch containing the Travis CI.
Currently our build is breaking on that branch because of bogus links. Once
I can get that branch to build successfully, I'll merge it with master!

**Comment by lwasser** [comment]
Ok. Sounds perfect! Thanks Max. so fun to work with someone on all of this! Lots of complementary skills and knowledge goes FAR! Have a terrific weekend.

l.

**Comment by lwasser** [comment]
goodness - no. see  	a36d3d1
fixed. sorry! i'm still playing with breadcrumbs too. this is why i don't like pushing the config file. i always forget these details. thanks for the catch!

**Comment by mbjoseph** [comment]
:smiley_cat:

**Pull request merged**
