### PR TITLE
SEO Update to Robots.txt

### PR DESCRIPTION
**Pull request by clelliott101**

### CODE REVIEW

**Comment by lwasser** [comment]
hey @kendrasand @clelliott101 when you submit 2 separate pull requests like this on the same file, you run the risk of a merge conflict. Please do not do that. rather - one of you makes changes to a file and submits ALL CHANGES. IN this case, one of you should update from the other's repo and resubmit so there aren't conflicts! i can explain more in person if need be.

**Comment by lwasser** [comment]
this conflict is very easy for me to resolve but if the file were more complex it would start to be very difficult to manage.

**Comment by kendrasand** [comment]
Hi Leah,

Thanks for sharing this information. I thought we could fork and pull in
layers. Good to know! We will make sure to do updates one at a time, giving
you time to review in between, in the future.

Hope it went smoothly otherwise! Have a great day.

-Kendra

**Comment by lwasser** [comment]
ok! this PR has been merged @clelliott101 @kendrasand

**Pull request merged**
