### PR TITLE
Validate topics and subtopics

### PR DESCRIPTION
**Pull request by mbjoseph**
This commmit adds functionality to verify that all topics and subtopics cited in posts satisfy the following conditions:

1. They exist in the _data/topics.yml file, which acts as our master list of valid topics and subtopics.

2. They have all required markdown files in org/topics/ to render pages on the site that list posts associated with each topic and subtopic.

The _data/topics.yml file must be maintained by a human.
Markdown files and associated topic directories in org/topics are autogenerated by processing-code/validate_topics.R.

### CODE REVIEW

**Comment by mbjoseph** [comment]
This solves #259

**Comment by mbjoseph** [comment]
Dang. Looks like Travis CI is failing in the case when we have an unused topic/subtopic page: https://travis-ci.org/earthlab/earthlab.github.io/builds/230940121

I suppose I could modify the validation script to only include pages that are going to have a nonzero number of posts associated with the topic or subtopic.

**Comment by mbjoseph** [comment]
Or maybe this is just raising errors where our current site has missing links... @lwasser what do you think? If I merge this, will the build pass again (after these pages are generated)?

**Comment by mbjoseph** [comment]
I suspect that once I merge this, the build will start passing again as these links are created. Let's see. If not I'll deal with the subsequent broken links!

**Comment by lwasser** [comment]
It will. The problem is that if the live site doesn’t have the md page travis fails. The config file is now testing against the live site
Can we fix this?  It’s going to be an ongoing issue. Can we force travis to use a config without the url so it builds a local version and doesn’t test against the live site?

**Comment by mbjoseph** [comment]
Good point - we should test against the generated site, not the deployed site. I don't know whether we can force travis to do this, but I'll open an issue.

**Comment by lwasser** [comment]
Great! It could be that all we need to do is adjust the config file to test prior to a final merge. Comment out the site.url entry which contains the base url. If we could force Travis to do that... life would be good.
L.

Leah A. Wasser
---
Director, Earth Analytics Education Initiative
Earth Lab, CU Boulder
twitter: @leahawasser

________________________________

**Pull request merged**
