### PR TITLE
update bootcamp to reflect new course

### LINKED ISSUE #994: Inverted hillshade colormap in lesson 6 for chapter 4 in intermediate textbook
This is the first time i file an issue on GitHub, so excuse me if I don't follow all conventions - just trying to help. :)

I have been working though the lessons in the intermediate earth data science textbook. Lesson 6 in chapter 4 ( https://www.earthdatascience.org/courses/use-data-open-source-python/intro-raster-data-python/fundamentals-raster-data/raster-data-exercises/ ) uses a hillshade dataset.

The "target" hillshade image looked a bit weird to me - the valley seemed to be "sticking up" and the buildings on the right side look like rectangular holes in the ground. However, if the hillshade is plotted with an inverted gray colormap, where the "high end" is white (e.g. "gray") it looks correct. 

I suggest changing the "target" plot images (for challenges 1-3), and changing the text to recommend using cmap="gray" rather than cmap="Grays".

Current image in textbook:

image

Hillshade plotted with "gray":

image

### PR DESCRIPTION
**Pull request by lwasser**
this  updates the bootcamp course but also closes #994 ! much better hillshade and fully up to date bootcamp content now!!

### CODE REVIEW

**Comment by nkorinek** [comment]
@lwasser this pr has had captions added to the images, appears to build well locally, and has had it's merge conflicts resolved!

**Comment by lwasser** [comment]
you rock @nkorinek i'll have a look later today or tomorrow!!

**Comment by lwasser** [comment]
@nkorinek what is #992  all about? do we need that PR ? this one doesn't have conflicts from what i can tell but perhaps i'm missing something

**Comment by nkorinek** [comment]
@lwasser we can get rid of #992 . It was to make sure I didn't break this PR. The changes on #992 went through just fine so I moved them over to this PR instead.

**Comment by lwasser** [comment]
ok @nkorinek i needed a mindless task to work on today and this hit the spot. i think we are just about done with this PR. i'll be merging shortly. i'm going to make a note that we need to move CI to actions from travis.

**Pull request merged**
