### PR TITLE
Switching out the matplotcheck & earthpy tool images for new ones that Ally made

### PR DESCRIPTION
**Pull request by lherwehe**
Hey @lwasser! Ally made new images for the matplotcheck and earthpy tool badges, I've switched the old for the new in this pull request. She also made larger version of each badge that would work for the banner, I see that you gave the new tools a blue banner which also looks good, but let me know if you want me to add the banner images (they're pngs but have a different file name so I'd update the text files)

### CODE REVIEW

**Comment by lherwehe** [comment]
oops @lwasser she named matplotcheck wrong, fixing now...

**Comment by lwasser** [comment]
oops @lherwehe we have a few merge conflicts here. did you update from master in earth lab before pushing this over?? this pr should only have 2 - 4 files in it. If you want, you can update your fork from master, recreate the images branch from that and then add the new files to it.

**Comment by lwasser** [comment]
@lherwehe you can work with @jlpalomino if you'd like to clean up this PR. i will merge it once the merge conflicts are fixed!! if not let's do it together in our next meeting. it would be nice to merge this however.

**Comment by lherwehe** [comment]
hi @lwasser! sorry about this. @jlpalomino helped me to fix it so it should be good to go now---just updated the matplotcheck and earthpy logos.

**Comment by lwasser** [comment]
awesome!! thank you @lherwehe merging.

**Pull request merged**
