### PR TITLE
Update day 1 lessons

### PR DESCRIPTION
**Pull request by jlpalomino**
@lwasser  These changes fix broken links and placement of captions for day 1 lessons and updates the optional challenge for day 1 lesson on git fork and clone to use GItHub classroom assignment.

### CODE REVIEW

**Comment by lwasser** [comment]
@jlpalomino  please also submit a PR with the notebooks to earth-analytics-python. or did i miss it?

**Comment by lwasser** [comment]
wonderful. Travis is happy with the files! merging and will push to master.

**Comment by jlpalomino** [comment]
@lwasser Thanks for the reminder. I did not submit the PR with the notebooks to earth-analytics-python. Will do that now.

**Comment by lwasser** [comment]
Thank you!

**Pull request merged**
