### PR TITLE
broken census link + progress bar fixed

### PR DESCRIPTION
**Pull request by mbjoseph**
The previous dev build was failing on Travis because of this census link. I've removed the link, and in the process fixed a bug in the progress bar for rendering posts, which would break when we had only one new thing to render.

### CODE REVIEW

**Comment by mbjoseph** [comment]
Fixed the build! 👍

**Comment by lwasser** [comment]
i'm getting a fail on on other lesson in dev-lessons - one of your tutorials. can you check it out?

https://travis-ci.org/earthlab/earthlab.github.io/builds/185559337

**Comment by lwasser** [comment]
actually let me merge with dev first.

**Comment by mbjoseph** [comment]
Cool - thanks for the heads up. I removed that link with PR #70

**Comment by lwasser** [comment]
Weird – it’s happy now. I am not sure why but… ALL IS WELL!!  Thanks!

**Pull request merged**
