### PR TITLE
Fix broken links - Nov 15th, 2019

### PR DESCRIPTION
**Pull request by allyfall**
@jlpalomino 

Fixed broken links on: 

earthdatascience.org/courses/earth-analytics/multispectral-remote-sensing-modis/normalized-burn-index-dNBR/
earthdatascience.org/courses/earth-analytics/remote-sensing-uncertainty/about-uncertainty-lidar/
earthdatascience.org/courses/earth-analytics/remote-sensing-uncertainty/
earthdatascience.org/courses/earth-analytics/using-apis-natural-language-processing-twitter/intro-to-social-media-text-mining-python/
earthdatascience.org/courses/earth-analytics/multispectral-remote-sensing-data/introduction-multispectral-imagery-r/
--
earthdatascience.org/courses/earth-analytics/multispectral-remote-sensing-data/landsat-data-in-r-geotiff/
earthdatascience.org/courses/earth-analytics/multispectral-remote-sensing-data/landsat-data-in-r-geotiff
earthdatascience.org/courses/earth-analytics/multispectral-remote-sensing-data/landsat-data-in-r-geotiff
earthdatascience.org/courses/earth-analytics/multispectral-remote-sensing-modis/
earthdatascience.org/courses/earth-analytics/document-your-science/
--
earthdatascience.org/courses/earth-analytics/get-data-using-apis/intro-to-programmatic-data-access-r/
earthdatascience.org/courses/earth-analytics/get-data-using-apis/leaflet-r/
earthdatascience.org/courses/earth-analytics/lidar-raster-data-r/explore-lidar-point-clouds-plasio/
earthdatascience.org/courses/earth-analytics-python/python-open-science-toolbox/how-rain-impacts-floods/
--
earthdatascience.org/courses/earth-analytics-python/python-open-science-toolbox/measure-changes-in-terrain-caused-by-floods/
earthdatascience.org/courses/earth-analytics/data-sources/

### CODE REVIEW

**Comment by lwasser** [comment]
@allyfall @jlpalomino  this is great. is there a related PR over in the lessons repo? can you please link to that here? i just want to ensure that these changes were on the original files :) 
excellent first pr @allyfall !!!

**Comment by jlpalomino** [comment]
Hey @lwasser the PR in earth-analytics-lessons is https://github.com/earthlab/earth-analytics-lessons/pull/466  I'll make a task for myself to review both.

**Comment by lwasser** [comment]
thank you so much @jlpalomino !!!

**Comment by jlpalomino** [comment]
Thanks @allyfall!  These changes look good and have been incorporated into the website.

**Pull request merged**
