### PR TITLE
Add blog posts on four must have skills and art of science blogging

### PR DESCRIPTION
**Pull request by jlpalomino**
@lwasser This PR adds the md and image files for blog post on four must have skills and the art of science blog.

### CODE REVIEW

**Comment by jlpalomino** [comment]
@lwasser The yaml has been fixed, so I believe that this PR is ready for merging. Let me know if there is still something else that needs to be done.

**Comment by jlpalomino** [comment]
@lwasser Actually, just noticed that the authors are not rendering locally at the top of the blog post. Please see my comment in the other PR: https://github.com/earthlab/earth-analytics-lessons/pull/322

**Comment by jlpalomino** [comment]
@lwasser This PR has been updated with the correct yaml for authors in the md file and is ready to merge. (Tested locally and looks good)

**Comment by lwasser** [comment]
@jlpalomino what is the status of the other blog post? can you add it as a pr too? that has an earlier date so i'd rather post that with this!! can you just add that to this PR ? i can build locally and test things and then push it to the live site!!

**Comment by jlpalomino** [comment]
@lwasser For the older post on the four skills in demand, I believe that @jvtcl was working on making sure that the plot footers would be generated through the eds-lessons-dev build? I'll check in with him about that.

**Comment by lwasser** [comment]
wonderful. i'm going to sit back and wait for that to get fixed!! this one is ahead of the other one so it would be posting out of order otherwise.

**Comment by jlpalomino** [comment]
@lwasser This PR now adds the md and image files for two blog posts: the four must have skills and art of science blogging.  Note that the two non-plot images needed for the blog post on four skills are already in [master of this repo](https://github.com/earthlab/earthlab.github.io/tree/master/images/blog/2019-03-18-four-must-have-skills-in-earth-data-science).

**Comment by lwasser** [comment]
yahoo!! @jlpalomino this looks GREAT locally. merging now. let's celebrate blogs building!!!

**Pull request merged**
