### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by lwasser**

### CODE REVIEW

**Comment by lwasser** [comment]
hey @mbjoseph i'd like to merge this into master today or tomorrow. Are you ok with that?
And if so, what is our process to stamp it as a "release" ? We can define release as a suite of new functionality vs content updates which i'll make frequently throughout the semester.

**Comment by lwasser** [comment]
plus. does this mean i am winning at life? i'm just saying this may go to my head ... all the positivity and success. 

screen shot 2017-01-12 at 11 00 40 am

**Comment by mbjoseph** [comment]
Nice! I think we can follow the instructions here https://help.github.com/articles/creating-releases/ to make a release once we've merged. 

I am going to play with this locally for a bit.

**Comment by mbjoseph** [comment]
This looks good to me. I'm ok with merging, but I'll let you do the honors!

**Comment by lwasser** [comment]
yay! ok i'm heading to a meeting. i'll do it this afternoon 👍 👍 👍 👍 👍 👍 👍  so excited @mbjoseph thanks!

**Pull request closed without merging**
