### PR TITLE
Spelling fixes from student feedback

### PR DESCRIPTION
**Pull request by nkorinek**
@lwasser hey! As you asked, here is the unmerged spelling fixes pr opened up here in io. The first pr with spelling fixes was already merged over at https://github.com/earthlab/earth-analytics-lessons . This is a pr for the one that is still open over there.

### CODE REVIEW

**Comment by lwasser** [comment]
thank you @nkorinek so this will cover all of the fixes that you've implemented?  much appreciated!!

**Comment by lwasser** [comment]
i do think i merged some of the typos that you fixed but wanted to check!

**Comment by nkorinek** [comment]
@lwasser yes! this was merged about two weeks ago that had a lot of spelling catches in it! https://github.com/earthlab/earth-analytics-lessons/pull/650

**Comment by lwasser** [comment]
awesome. thank you @nkorinek !!

**Pull request merged**
