### PR TITLE
adding license to site

### PR DESCRIPTION
**Pull request by lwasser**
@mbjoseph  testing this out. added JUST the license file. still need to update more files. 
if it looks ok please merge.

### CODE REVIEW

**Comment by mbjoseph** [comment]
Looks good to me - I added a dash, since it looked to me like "EARTH LAB VIEW LICENSE", and I though tit might be nice to break it up into "EARTH LAB - VIEW LICENSE". Feel free to revert if you like it better the first way! :)

**Comment by lwasser** [comment]
@mbjoseph i have a few things to learn about branches. So - you can add to the PR? Because i added changes to dev and then you did on top of my changes and all of those changes go into the PR. that's actually a much nicer workflow. i like it. 

re the license - i like the dash! i think eventually i may add it to the bottom of the lessons like data carpentry does but right now i don't like the  bottom of our lessons so i'm gonna leave them alone till i have time to work on the design of them :) ok i'll merge this!

**Comment by mbjoseph** [comment]
Awesome possum. Yep so I just did a 

```
git pull
git checkout dev
<<changed things>>
git commit -a -m 'blah blah blah' 
git push
```

and voila!

Thanks for adding this license page! We could also think about tossing in a badge (e.g., http://mbjoseph.github.io/blog.html) if you're into badges.

**Comment by lwasser** [comment]
ahhh - commit -am does the add and commit in one swoop if you are adding all? is that right? 

btw - the _drafts folder is where ou can store stuff u don't want to publish yet! AND you can run 
bundle exec jekyll serve --drafts to render the site with all of the drafts folders published locally! boo yah!

**Comment by lwasser** [comment]
:1 on the badge - i'll think about how to make it look nice in our footer!

**Pull request merged**
