### PR TITLE
Pushing current files to master

### PR DESCRIPTION
**Pull request by lwasser**
@mbjoseph i went through and updated ALL files that i've worked on in the dev site, encapsulated in this PR you can see each commit to better understand what i'm adding. It's mostly small. The largest change is a `_drafts` folder which contains all the content i'm working on currently. 

COOLNESS - run bundle exec jekyll serve --drafts to see them live!

### CODE REVIEW

**Comment by mbjoseph** [comment]
Thanks - this is super useful! I am getting a build error when generating the site with the --drafts argument:

```bash
bundle exec jekyll serve --drafts
```

Gives me:

```
Configuration file: /Users/majo3748/Documents/earthlab/earthlab.github.io/_config.yml
            Source: /Users/majo3748/Documents/earthlab/earthlab.github.io
       Destination: /Users/majo3748/Documents/earthlab/earthlab.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
             Error: could not read file /Users/majo3748/Documents/earthlab/earthlab.github.io/_drafts/course-materials/geog-4100-5100/co-floods-2-data-r/COOP-NEIS-Precipitation-In-R.Rmd: (<unknown>): found character that cannot start any token while scanning for the next token at line 8 column 15
             Error: could not read file /Users/majo3748/Documents/earthlab/earthlab.github.io/_drafts/course-materials/geog-4100-5100/co-floods-2-data-r/USGS-Stream-Discharge-In-R.Rmd: (<unknown>): found character that cannot start any token while scanning for the next token at line 8 column 15
             Error: could not read file /Users/majo3748/Documents/earthlab/earthlab.github.io/_drafts/course-materials/geog-4100-5100/intro-knitr-rmd/Rmd04-code-chunks.Rmd: (<unknown>): found character that cannot start any token while scanning for the next token at line 8 column 15
             Error: could not read file /Users/majo3748/Documents/earthlab/earthlab.github.io/_drafts/course-materials/geog-4100-5100/intro-knitr-rmd/Rmd05-knitr.Rmd: (<unknown>): found character that cannot start any token while scanning for the next token at line 8 column 15
        Pagination: Pagination is enabled, but I couldn't find an index.html page to use as the pagination template. Skipping pagination.
      Invalid Date: '' is not a valid datetime.
  Liquid Exception: exit in sitemap.xml
```

**Comment by mbjoseph** [comment]
I can serve without the drafts argument, so I suspect this is something related to files in the _drafts directory.

**Comment by lwasser** [comment]
OOPS – yea I have to push _config changes. The rmd files should be IGNORED. I don’t like to push my config file up so they aren’t there. one minute. It will work when you have this update.

**Comment by lwasser** [comment]
Yup – try again after you pull the new config file. Make sure your config has “.Rmd” in the ignore list which is the change I made!
NOTE: you won’t see the full list of lessons on the course lessons page because I created that from a yaml list and hide items manually using a yaml field. If you know the link you can still see them though which allows me to work locally.
```
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - "*.Rmd"
```
Leah

**Comment by mbjoseph** [comment]
This looks great! I'm going to go ahead and merge.

**Comment by lwasser** [comment]
Yee haw!!!

**Pull request merged**
